import type { ZuploContext, ZuploRequest } from "@zuplo/runtime";
import { invokeJson } from "@zuplo/starter-kit-shared/mcp";
import type { Payout } from "../repositories/payouts.ts";
import type { Credit } from "../repositories/credits.ts";
import type { CompPlan } from "../repositories/comp-plans.ts";
import { callClaude } from "../integrations/claude.ts";

/**
 * Orchestrator MCP tool: explain_commission_amount.
 *
 * Given a payoutId, walks the payout, the credits that fed it, and the
 * comp plan that priced it. Returns a step-by-step structured breakdown
 * AND a plain-English explanation generated by Claude — exactly what a
 * rep needs to read when they ask "where does this number come from?".
 *
 * This is the kit's "AI angle". Comp plans are notoriously
 * hard-to-explain spaghetti; the structured math gives the LLM
 * everything it needs to ground its answer.
 */

interface Body {
  payoutId: string;
  /** When false, skip the Claude call and only return the structured math. */
  generateExplanation?: boolean;
}

interface CreditPage {
  items: Credit[];
  nextCursor: string | null;
}

interface PlanPage {
  items: CompPlan[];
  nextCursor: string | null;
}

export default async function (request: ZuploRequest, context: ZuploContext) {
  const body = (await request.json()) as Body;
  const auth = { authorization: request.headers.get("authorization") ?? "" };

  const payout = await invokeJson<Payout>(context, `/payouts/${body.payoutId}`, {
    headers: auth,
  });

  // Find the comp plan whose period matches. Plans are not directly
  // referenced from a payout, so we resolve by period.
  const plans: CompPlan[] = [];
  let pCursor: string | null | undefined = undefined;
  do {
    const qs = new URLSearchParams({ limit: "200" });
    if (pCursor) qs.set("cursor", pCursor);
    const page = await invokeJson<PlanPage>(context, `/plans?${qs}`, { headers: auth });
    plans.push(...page.items);
    pCursor = page.nextCursor;
    if (plans.length > 1000) break;
  } while (pCursor);
  const plan = plans.find((p) => p.period === payout.period) ?? null;

  // Collect credits that fed this payout: same rep + same period.
  const credits: Credit[] = [];
  let cCursor: string | null | undefined = undefined;
  do {
    const qs = new URLSearchParams({ limit: "200" });
    if (cCursor) qs.set("cursor", cCursor);
    const page = await invokeJson<CreditPage>(context, `/credits?${qs}`, { headers: auth });
    for (const c of page.items) {
      if (c.repEmail === payout.repEmail && c.period === payout.period) {
        credits.push(c);
      }
    }
    cCursor = page.nextCursor;
    if (credits.length > 5000) break;
  } while (cCursor);

  const creditBreakdown = credits.map((c) => {
    const credited = Math.round(c.amountCents * (c.splitPercent / 100));
    return {
      creditId: c.id,
      dealId: c.dealId,
      amountCents: c.amountCents,
      splitPercent: c.splitPercent,
      creditedCents: credited,
      dealStatus: c.dealStatus ?? null,
    };
  });
  const baseSum = creditBreakdown.reduce((s, c) => s + c.creditedCents, 0);

  // Reproduce the accelerator decision so we can name which tier triggered.
  const sortedAcc = plan ? [...plan.accelerators].sort((a, b) => b.threshold - a.threshold) : [];
  const tierApplied = sortedAcc.find((tier) => payout.attainmentPercent >= tier.threshold) ?? null;
  const baseRate = plan?.baseRate ?? null;
  const effectiveRate =
    tierApplied?.rate ?? (baseRate !== null ? baseRate : null);

  const expectedCommission =
    baseRate !== null && effectiveRate !== null
      ? Math.round(baseSum * effectiveRate)
      : null;

  const math = {
    creditBreakdown,
    baseAmountCents: baseSum,
    attainmentPercent: payout.attainmentPercent,
    baseRate,
    tierApplied,
    effectiveRate,
    accelerator: payout.accelerator,
    commissionCents: payout.commissionCents,
    recomputedCommissionCents: expectedCommission,
    matchesStored:
      expectedCommission !== null && expectedCommission === payout.commissionCents,
  };

  // Generate a plain-English explanation via Claude unless caller opts out.
  let explanation: string | undefined;
  if (body.generateExplanation !== false) {
    try {
      const dollars = (cents: number | null) =>
        cents === null ? "n/a" : `$${(cents / 100).toFixed(2)}`;
      const facts = [
        `Rep: ${payout.repEmail}`,
        `Period: ${payout.period}`,
        `Plan: ${plan?.name ?? "(no matching plan found)"}`,
        `Quota attainment: ${payout.attainmentPercent}%`,
        `Base rate: ${baseRate === null ? "n/a" : `${(baseRate * 100).toFixed(1)}%`}`,
        tierApplied
          ? `Accelerator triggered: ${(tierApplied.rate * 100).toFixed(1)}% (threshold ${tierApplied.threshold}%)`
          : "No accelerator triggered",
        `Effective rate: ${effectiveRate === null ? "n/a" : `${(effectiveRate * 100).toFixed(1)}%`}`,
        `Sum of credited amounts: ${dollars(baseSum)} across ${creditBreakdown.length} credit(s)`,
        `Commission paid: ${dollars(payout.commissionCents)}`,
        `Recomputed commission: ${dollars(expectedCommission)}`,
        `Matches stored: ${math.matchesStored}`,
      ];
      const claude = await callClaude({
        system:
          "You are a comp ops analyst writing to a sales rep. Explain how this commission number was computed in plain English. Be concrete about which credits, which rate, and whether an accelerator triggered. Be honest if the recomputation does not match the stored number. Keep it under 180 words. Use plain prose.",
        messages: [
          {
            role: "user",
            content: `Explain this commission breakdown:\n\n${facts.join("\n")}`,
          },
        ],
        maxTokens: 600,
      });
      explanation = claude.text.trim();
    } catch (err) {
      context.log.warn(
        `Claude explanation failed: ${(err as Error).message}`,
      );
    }
  }

  return new Response(
    JSON.stringify({ payout, plan, math, explanation }),
    { headers: { "content-type": "application/json" } },
  );
}
